-- GENERATED by scripts/generate-supabase-seed.ts — do not edit by hand.
-- Mirrors src/lib/content/perfumes.ts + settings.ts.

begin;

truncate table public.perfume_images, public.fragrance_notes,
  public.perfume_sizes, public.perfumes restart identity cascade;
delete from public.site_settings;

insert into public.site_settings (id, brand_name, tagline, description, announcement,
  primary_nav, footer_nav, social, contact_email, address_lines, currency,
  logo_url, favicon_url, hero_headline, hero_intro, homepage_intro, brand_story)
values (
  'default', 'Maison Lumière', 'Parfums d''Auteur — Paris', $txt$Maison Lumière is a small Parisian perfume house. Each composition is signed by its perfumer and made in limited batches, without reformulation.$txt$, 'Complimentary engraving and shipping on orders over $200',
  '[{"label":"Collection","href":"/collection"},{"label":"The House","href":"/#house"},{"label":"Notes","href":"/#notes"}]'::jsonb, '[{"label":"Collection","href":"/collection"},{"label":"Contact","href":"/#contact"},{"label":"Admin","href":"/admin"}]'::jsonb, '[{"label":"Instagram","href":"https://instagram.com"},{"label":"Pinterest","href":"https://pinterest.com"}]'::jsonb,
  'atelier@maisonlumiere.example', ARRAY['9 Rue de Sévigné', '75004 Paris', 'France']::text[], 'USD',
  null, null,
  $txt$The scent of
a room at dusk$txt$, $txt$Maison Lumière is a small Parisian house making auteur perfumes — each one signed, made in limited batches, and left exactly as it was composed.$txt$,
  $txt$A small house, run deliberately slowly. One accord at a time, signed by the nose, made in small batches, kept as it was.$txt$, $txt$Maison Lumière is a small Parisian perfume house. Each composition is signed by its perfumer and made in limited batches, without reformulation.$txt$
);

-- Lumière Noire
insert into public.perfumes (id, slug, name, concentration, family, tagline,
  description, perfumer, year, accent, featured, availability, display_order, is_published)
values (
  '45f78837-49a5-49a4-8167-a12f3acff9db', 'lumiere-noire', 'Lumière Noire', 'Extrait de Parfum', 'Amber', 'Amber and incense held in a low, unhurried glow.',
  $txt$Lumière Noire begins where the evening turns inward. Labdanum and benzoin are warmed slowly, then drawn back by a thread of frankincense so the sweetness never settles into comfort.

Worn close to the skin it reads as candlelight in a dark room — present, deliberate, impossible to place until you are near.$txt$, 'Élodie Rançon', 2021, '#b98a4b', true, 'available', 1, true
);
insert into public.perfume_sizes (perfume_id, ml, price, display_order) values
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 50, 245, 0),
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 100, 365, 1);
insert into public.fragrance_notes (perfume_id, name, tier, description, display_order) values
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 'Pink Pepper', 'top', 'a dry spark struck at the opening', 0),
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 'Saffron', 'top', 'leathered, faintly medicinal warmth', 1),
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 'Labdanum', 'heart', 'resinous amber, the spine of the scent', 2),
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 'Frankincense', 'heart', 'cool smoke that keeps the amber honest', 3),
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 'Benzoin', 'base', 'vanillic resin, soft and slow', 4),
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 'Vetiver', 'base', 'a shadow of earth beneath', 5);
insert into public.perfume_images (perfume_id, role, path, alt, display_order) values
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 'hero', '/images/noire-atmosphere.svg', 'Amber light diffused through darkness', 0),
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 'gallery', '/images/noire-bottle.svg', 'Lumière Noire flacon, front view', 0),
  ('45f78837-49a5-49a4-8167-a12f3acff9db', 'gallery', '/images/noire-atmosphere.svg', 'Warm amber atmosphere', 1);

-- Fleur d'Ombre
insert into public.perfumes (id, slug, name, concentration, family, tagline,
  description, perfumer, year, accent, featured, availability, display_order, is_published)
values (
  'f0514274-ac68-484e-8fa8-facee2bb2906', 'fleur-dombre', 'Fleur d''Ombre', 'Eau de Parfum', 'Floral', 'Tuberose in half-light, cooled by iris and clean musk.',
  $txt$A white flower composition built for restraint. Tuberose and jasmine are given room to breathe, then shaded with orris butter until the effect is powdery rather than heady.

The drydown is quiet skin musk — the flowers recede but never quite leave.$txt$, 'Marc Vaugelas', 2019, '#c98f9b', true, 'available', 2, true
);
insert into public.perfume_sizes (perfume_id, ml, price, display_order) values
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 30, 135, 0),
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 50, 195, 1),
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 100, 285, 2);
insert into public.fragrance_notes (perfume_id, name, tier, description, display_order) values
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 'Green Mandarin', 'top', 'a cold citrus edge', 0),
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 'Pear Blossom', 'top', 'watery, translucent', 1),
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 'Tuberose', 'heart', 'creamy, narcotic, held in check', 2),
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 'Orris Butter', 'heart', 'silver, powdery, expensive', 3),
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 'White Musk', 'base', 'laundered warmth', 4),
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 'Sandalwood', 'base', 'a soft milky floor', 5);
insert into public.perfume_images (perfume_id, role, path, alt, display_order) values
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 'hero', '/images/fleur-atmosphere.svg', 'Soft rose-grey light', 0),
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 'gallery', '/images/fleur-bottle.svg', 'Fleur d''Ombre flacon, front view', 0),
  ('f0514274-ac68-484e-8fa8-facee2bb2906', 'gallery', '/images/fleur-atmosphere.svg', 'Rose-grey atmosphere', 1);

-- Bois Cendré
insert into public.perfumes (id, slug, name, concentration, family, tagline,
  description, perfumer, year, accent, featured, availability, display_order, is_published)
values (
  '5582542e-cbb9-4f7e-8dd0-7cf800307430', 'bois-cendre', 'Bois Cendré', 'Eau de Parfum', 'Woody', 'Dry cedar and a curl of woodsmoke over warm paper.',
  $txt$Bois Cendré is the smell of a room the morning after a fire has burned down. Cedar and guaiac wood carry a soft ash note, kept from going grey by a little tonka.

It sits on the skin as texture more than sweetness — matte, sober, and long.$txt$, 'Élodie Rançon', 2022, '#9a7b5a', true, 'available', 3, true
);
insert into public.perfume_sizes (perfume_id, ml, price, display_order) values
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 50, 185, 0),
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 100, 265, 1);
insert into public.fragrance_notes (perfume_id, name, tier, description, display_order) values
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 'Cypress', 'top', 'cold, coniferous, clarifying', 0),
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 'Cardamom', 'top', 'a dry aromatic lift', 1),
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 'Cedar', 'heart', 'sharpened pencil shavings', 2),
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 'Guaiac Wood', 'heart', 'the smoke, tarry and warm', 3),
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 'Tonka Bean', 'base', 'hay-like, just off sweet', 4),
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 'Cashmeran', 'base', 'a soft woody haze', 5);
insert into public.perfume_images (perfume_id, role, path, alt, display_order) values
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 'hero', '/images/bois-atmosphere.svg', 'Ashen brown light', 0),
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 'gallery', '/images/bois-bottle.svg', 'Bois Cendré flacon, front view', 0),
  ('5582542e-cbb9-4f7e-8dd0-7cf800307430', 'gallery', '/images/bois-atmosphere.svg', 'Ashen wood atmosphere', 1);

-- Sel & Iris
insert into public.perfumes (id, slug, name, concentration, family, tagline,
  description, perfumer, year, accent, featured, availability, display_order, is_published)
values (
  'c140339f-4f71-4527-828f-cf595b03e078', 'sel-et-iris', 'Sel & Iris', 'Eau de Parfum', 'Chypre', 'Mineral salt air pulled across cold, earthy orris.',
  $txt$A modern chypre without the oakmoss weight. Iris root gives the grey, ambrette gives the skin, and a saline accord keeps the whole thing moving like wind off water.

Bright at a distance, quietly bitter up close.$txt$, 'Naomi Feldt', 2020, '#8fa39b', false, 'available', 4, true
);
insert into public.perfume_sizes (perfume_id, ml, price, display_order) values
  ('c140339f-4f71-4527-828f-cf595b03e078', 50, 205, 0),
  ('c140339f-4f71-4527-828f-cf595b03e078', 100, 295, 1);
insert into public.fragrance_notes (perfume_id, name, tier, description, display_order) values
  ('c140339f-4f71-4527-828f-cf595b03e078', 'Bergamot', 'top', 'clean, faceted citrus', 0),
  ('c140339f-4f71-4527-828f-cf595b03e078', 'Sea Salt Accord', 'top', 'mineral, almost cold', 1),
  ('c140339f-4f71-4527-828f-cf595b03e078', 'Orris Root', 'heart', 'carrot-earth, rooty, grey', 2),
  ('c140339f-4f71-4527-828f-cf595b03e078', 'Ambrette Seed', 'heart', 'musky, pear-skin softness', 3),
  ('c140339f-4f71-4527-828f-cf595b03e078', 'Patchouli', 'base', 'a dry, cleaned-up base', 4),
  ('c140339f-4f71-4527-828f-cf595b03e078', 'Ambergris Accord', 'base', 'warm salt on skin', 5);
insert into public.perfume_images (perfume_id, role, path, alt, display_order) values
  ('c140339f-4f71-4527-828f-cf595b03e078', 'hero', '/images/iris-atmosphere.svg', 'Cold blue-grey light', 0),
  ('c140339f-4f71-4527-828f-cf595b03e078', 'gallery', '/images/iris-bottle.svg', 'Sel & Iris flacon, front view', 0),
  ('c140339f-4f71-4527-828f-cf595b03e078', 'gallery', '/images/iris-atmosphere.svg', 'Blue-grey atmosphere', 1);

-- Cuir Blanc
insert into public.perfumes (id, slug, name, concentration, family, tagline,
  description, perfumer, year, accent, featured, availability, display_order, is_published)
values (
  '77aa71bd-c11b-41e8-853b-d429481fd3ca', 'cuir-blanc', 'Cuir Blanc', 'Extrait de Parfum', 'Leather', 'A pale, suede-soft leather brushed with orange flower.',
  $txt$Leather without the smoke. A birch-free suede accord is lifted with neroli and a little beeswax, so it stays close to the colour of unfinished hide.

Refined, slightly austere, and unmistakably a signature.$txt$, 'Marc Vaugelas', 2018, '#c7ac7c', false, 'available', 5, true
);
insert into public.perfume_sizes (perfume_id, ml, price, display_order) values
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 50, 265, 0),
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 100, 385, 1);
insert into public.fragrance_notes (perfume_id, name, tier, description, display_order) values
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 'Neroli', 'top', 'green, honeyed orange flower', 0),
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 'Aldehydes', 'top', 'a lifted, soapy shimmer', 1),
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 'Suede Accord', 'heart', 'matte, powdery leather', 2),
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 'Orange Flower Absolute', 'heart', 'indolic warmth', 3),
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 'Beeswax', 'base', 'waxy, faintly sweet', 4),
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 'Tonka Bean', 'base', 'a soft almond floor', 5);
insert into public.perfume_images (perfume_id, role, path, alt, display_order) values
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 'hero', '/images/cuir-atmosphere.svg', 'Warm champagne light', 0),
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 'gallery', '/images/cuir-bottle.svg', 'Cuir Blanc flacon, front view', 0),
  ('77aa71bd-c11b-41e8-853b-d429481fd3ca', 'gallery', '/images/cuir-atmosphere.svg', 'Champagne atmosphere', 1);

-- Zeste Céleste
insert into public.perfumes (id, slug, name, concentration, family, tagline,
  description, perfumer, year, accent, featured, availability, display_order, is_published)
values (
  '3a90b307-258b-426d-811c-170bc890cdb9', 'zeste-celeste', 'Zeste Céleste', 'Eau de Toilette', 'Citrus', 'Cold-pressed citron and petitgrain over pale musk.',
  $txt$A citrus built to last longer than citrus usually does. Citron and grapefruit are anchored with petitgrain and a whisper of vetiver, so the brightness has something to hold onto.

Morning-clean, but never sharp.$txt$, 'Naomi Feldt', 2023, '#d9c07a', false, 'available', 6, true
);
insert into public.perfume_sizes (perfume_id, ml, price, display_order) values
  ('3a90b307-258b-426d-811c-170bc890cdb9', 50, 145, 0),
  ('3a90b307-258b-426d-811c-170bc890cdb9', 100, 210, 1);
insert into public.fragrance_notes (perfume_id, name, tier, description, display_order) values
  ('3a90b307-258b-426d-811c-170bc890cdb9', 'Citron', 'top', 'zesty, bittersweet peel', 0),
  ('3a90b307-258b-426d-811c-170bc890cdb9', 'Pink Grapefruit', 'top', 'juicy, faintly sulphurous', 1),
  ('3a90b307-258b-426d-811c-170bc890cdb9', 'Petitgrain', 'heart', 'green bitter-orange twig', 2),
  ('3a90b307-258b-426d-811c-170bc890cdb9', 'Neroli', 'heart', 'a soft floral bridge', 3),
  ('3a90b307-258b-426d-811c-170bc890cdb9', 'Vetiver', 'base', 'a thin rooty anchor', 4),
  ('3a90b307-258b-426d-811c-170bc890cdb9', 'White Musk', 'base', 'clean, weightless', 5);
insert into public.perfume_images (perfume_id, role, path, alt, display_order) values
  ('3a90b307-258b-426d-811c-170bc890cdb9', 'hero', '/images/zeste-atmosphere.svg', 'Pale gold light', 0),
  ('3a90b307-258b-426d-811c-170bc890cdb9', 'gallery', '/images/zeste-bottle.svg', 'Zeste Céleste flacon, front view', 0),
  ('3a90b307-258b-426d-811c-170bc890cdb9', 'gallery', '/images/zeste-atmosphere.svg', 'Pale gold atmosphere', 1);

commit;
