/**
 * Regenerates `supabase/seed.sql` from the sample content in
 * `src/lib/content/perfumes.ts` and `settings.ts`, so a freshly-seeded database
 * renders the exact same storefront as MockContentRepository.
 *
 *   node --experimental-strip-types scripts/generate-supabase-seed.ts
 *   (or plain `node scripts/generate-supabase-seed.ts` on Node >= 22.6)
 *
 * Run it again whenever the sample data changes. Once the Admin phase makes the
 * database authoritative this file is only a first-run convenience.
 */

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PERFUMES } from "../src/lib/content/perfumes.ts";
import { SITE_SETTINGS } from "../src/lib/content/settings.ts";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, "..", "supabase", "seed.sql");

/** Deterministic UUID (v4-shaped) from a stable string. */
function uuidFor(key: string): string {
  const h = createHash("md5").update(`maison-lumiere:${key}`).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const txt = (s: string) => `$txt$${s}$txt$`;
const jsonb = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (items: string[]) =>
  `ARRAY[${items.map(q).join(", ")}]::text[]`;

const lines: string[] = [];
lines.push(
  "-- GENERATED by scripts/generate-supabase-seed.ts — do not edit by hand.",
  "-- Mirrors src/lib/content/perfumes.ts + settings.ts.",
  "",
  "begin;",
  "",
  "truncate table public.perfume_images, public.fragrance_notes,",
  "  public.perfume_sizes, public.perfumes restart identity cascade;",
  "delete from public.site_settings;",
  "",
);

// -- site_settings ------------------------------------------------------------
const s = SITE_SETTINGS;
lines.push(
  "insert into public.site_settings (id, brand_name, tagline, description, announcement,",
  "  primary_nav, footer_nav, social, contact_email, address_lines, currency,",
  "  logo_url, favicon_url, hero_headline, hero_intro, homepage_intro, brand_story)",
  "values (",
  `  'default', ${q(s.brandName)}, ${q(s.tagline)}, ${txt(s.description)}, ${q(s.announcement)},`,
  `  ${jsonb(s.primaryNav)}, ${jsonb(s.footerNav)}, ${jsonb(s.social)},`,
  `  ${q(s.contactEmail)}, ${arr(s.addressLines)}, ${q(s.currency)},`,
  `  ${s.logoUrl ? q(s.logoUrl) : "null"}, ${s.faviconUrl ? q(s.faviconUrl) : "null"},`,
  `  ${s.heroHeadline ? txt(s.heroHeadline) : "null"}, ${s.heroIntro ? txt(s.heroIntro) : "null"},`,
  `  ${s.homepageIntro ? txt(s.homepageIntro) : "null"}, ${s.brandStory ? txt(s.brandStory) : "null"}`,
  ");",
  "",
);

// -- perfumes + children ----------------------------------------------------
for (const p of PERFUMES) {
  const id = uuidFor(p.slug);
  lines.push(
    `-- ${p.name}`,
    "insert into public.perfumes (id, slug, name, concentration, family, tagline,",
    "  description, perfumer, year, accent, featured, availability, display_order, is_published)",
    "values (",
    `  ${q(id)}, ${q(p.slug)}, ${q(p.name)}, ${q(p.concentration)}, ${q(p.family)}, ${q(p.tagline)},`,
    `  ${txt(p.description)}, ${q(p.perfumer)}, ${p.year}, ${q(p.accent)}, ${p.featured}, 'available', ${p.order}, true`,
    ");",
  );

  const sizeRows = p.sizes.map(
    (size, i) => `  (${q(id)}, ${size.ml}, ${size.price}, ${i})`,
  );
  lines.push(
    "insert into public.perfume_sizes (perfume_id, ml, price, display_order) values",
    sizeRows.join(",\n") + ";",
  );

  const noteRows = p.notes.map(
    (n, i) =>
      `  (${q(id)}, ${q(n.name)}, ${q(n.tier)}, ${n.description ? q(n.description) : "null"}, ${i})`,
  );
  lines.push(
    "insert into public.fragrance_notes (perfume_id, name, tier, description, display_order) values",
    noteRows.join(",\n") + ";",
  );

  const imageRows = [
    `  (${q(id)}, 'hero', ${q(p.hero.src)}, ${q(p.hero.alt)}, 0)`,
    ...p.gallery.map(
      (g, i) => `  (${q(id)}, 'gallery', ${q(g.src)}, ${q(g.alt)}, ${i})`,
    ),
  ];
  lines.push(
    "insert into public.perfume_images (perfume_id, role, path, alt, display_order) values",
    imageRows.join(",\n") + ";",
    "",
  );
}

lines.push("commit;", "");

writeFileSync(outFile, lines.join("\n"), "utf8");
console.log(`Wrote ${outFile} (${PERFUMES.length} perfumes).`);
